---
kind: pipeline
name: build-styled-media
steps:
  - commands:
      - 'npm install'
      - 'npm config set "//registry.npmjs.org/:_authToken" "$NPM_AUTH_TOKEN"'
      - 'npm publish'
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    name: npm
    image: node
