---
kind: pipeline
name: build-styled-media
steps:
  - commands:
      - 'npm install'
      - 'npm version patch'
      - 'npm adduser <<! $NPM_USERNAME $NPM_PASSWORD $NPM_EMAIL !'
      - 'npm publish'
    environment:
      NPM_EMAIL: caio@caiodev.com
      NPM_PASSWORD:
        from_secret: npm_password
      NPM_USERNAME: caiohenriquesilva
    name: npm
    image: node
